#!/usr/bin/env ruby

require 'webrick'
require 'open3'
require 'trollop'

OPTS = Trollop::options do
  banner "Usage: svcize [options] <cmd> [args...]"
  stop_on_unknown

  opt :port, "The HTTP Port to listen to", :default => 8080, :type => :int
  opt :type, "The Content-Type header to return", :default => "text/plain", :type => :string
end

if ARGV.size == 0 then
  warn "Missing command. Use svcize -h for more info."
  exit 1
end

server = WEBrick::HTTPServer.new :Port => OPTS[:port]

class Cmd < WEBrick::HTTPServlet::AbstractServlet
  def do_GET(request, response)
    env = ENV.to_hash.merge(request.query)
    env["request-path"] = request.path
    request.each do |k, v|
      env[k] = v
    end

    cmd = ARGV.map do |arg|
      arg.gsub(/%([A-Za-z0-9_\-]*?)%/) do |e|
        env[$1] 
      end
    end

    puts cmd.join(" ")

    output, status = Open3.capture2e(env, *cmd, :stdin_data => request.body)
    response.body = output
    response["Content-Type"] = OPTS[:contenttype]
    response["Exit-Status"] = status.exitstatus
    return (status.exitstatus == 0 ? 200 : 503)
  end
end

server.mount "/", Cmd
server.start

